name = "CurveFitParameters"
uuid = "75b670ed-29d0-4b9b-bcd2-edac41b9c208"
authors = ["Bryson Cale <bryson.cale1@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
